# Generated by Django 2.0.13 on 2019-07-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('cod_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=200)),
            ],
        ),
    ]
