# Generated by Django 2.0.13 on 2019-07-18 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ControlDepot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulo',
            name='count_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulo',
            name='f_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articulo',
            name='f_venc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articulo',
            name='time_stock',
            field=models.IntegerField(default=0),
        ),
    ]
